Сингулярное разложение матриц

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [1]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

In [2]:
A = np.array([[1, 2, 0], [0 ,0 ,5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])

In [3]:
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [4]:
U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [6]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.825 0.    0.   ]
 [0.    6.141 0.   ]
 [0.    0.    2.533]
 [0.    0.    0.   ]
 [0.    0.    0.   ]]


In [7]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.171  0.157 -0.531 -0.799 -0.162]
 [ 0.393 -0.529  0.613 -0.434  0.031]
 [-0.144 -0.824 -0.524  0.14   0.074]
 [ 0.888  0.061 -0.247  0.378 -0.06 ]
 [ 0.081  0.108 -0.082 -0.105  0.982]]


In [8]:
print(np.dot(U.T, U))

[[ 1.  0. -0. -0. -0.]
 [ 0.  1.  0.  0.  0.]
 [-0.  0.  1. -0. -0.]
 [-0.  0. -0.  1. -0.]
 [-0.  0. -0. -0.  1.]]


In [9]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.071 -0.367 -0.927]
 [ 0.717  0.665 -0.208]
 [ 0.693 -0.65   0.311]]


In [10]:
print(np.dot(V.T, V))

[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]


In [11]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

а) евклидова норма;

In [12]:
max(s)

8.824868854820442

б) норма Фробениуса.

In [13]:
np.linalg.norm(s)

11.04536101718726