Матрицы и матричные операции. Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а) Обе неопределены
б) АВ 2 х 3, ВА - неопределена
в) АВ - 8 х 8, ВА - 3 х 3
г) АВ и ВА - 4 х 4 

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(a + b)

[[ 5 -3]
 [ 3  5]]


In [ ]:
print(np.dot(a,b))
print(np.dot(b,a))

[[  4 -11]
 [ 12  -3]]
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    

In [ ]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
print(3*a - 2* b+ 4*c)

[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [ ]:
a = np.array([[4, 1], [5, -2], [2, 3]])
a_t = a.T
print(np.dot(a, a_t))

[[17 18 11]
 [18 29  4]
 [11  4 13]]


In [ ]:
print(np.dot(a_t, a))

[[45  0]
 [ 0 14]]


Матрицы и матричные операции. Часть 2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

а) $$sinx^2 + cosx^2 = 1.$$

б)

In [9]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(np.linalg.det(a))

180.0


в)

In [10]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.linalg.det(b))

0.0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

a) 4 * 4 = 16

б) $det(A^{T}) = det(A) = 4$

d) 2 * 4 = 8

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Матрица вырожденная если определитель равен нулю

In [13]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(np.linalg.det(a))

0.0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [14]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [15]:
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r = np.linalg.matrix_rank(b)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
